apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "httpbin"
  namespace: "strigus"
spec:
  selector:
     matchLabels:
       app: httpbin
  portLevelMtls:
    8080:
      mode: STRICT