#apiVersion: "networking.istio.io/v1alpha3"
apiVersion: networking.istio.io/v1beta1
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "giropops"
spec:
  host: "*.giropops.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL