#apiVersion: networking.istio.io/v1alpha3
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
 name: "httpbin-girus"
 namespace: "girus"
spec:
 host: "httpbin.girus.svc.cluster.local"
 trafficPolicy:
   tls:
     mode: DISABLE