#apiVersion: "authentication.istio.io/v1alpha1"
apiVersion: security.istio.io/v1beta1
kind: "Policy"
metadata:
  name: "httpbin"
  namespace: strigus
spec:
  targets:
  - name: httpbin
  peers:
  - mtls: {}